--- 
- 
  connection: local
  gather_facts: false
  hosts: netdevops_IOS
  name: "Get ARP information"

  vars:
    ios_provider:
      username: developer
      password: C1sco12345
  
  tasks: 
    - name: "show run backup"
      ios_command:
        provider: "{{ ios_provider }}"
        commands: 
          - show running      
      register: config

    - name: save output to ~/etc/ansible/backups/
      copy:
        content: "{{config.stdout[0]}}"
        dest: "/etc/ansible/backups/{{inventory_hostname}}-backup.txt"

